### ISSUE TITLE
MD-TABPANEL md-dynamic-height not working.

### ISSUE THREAD

**Issue by shannema** [Servoy/angularmaterial#1]
I would like to use dynamic height to prevent scroll-bars into the tabforms. 
When you add the md-dynamic-height attribute to the MD-TABS it is not working ok. 

I think the problem is with the MD-TAB-BODY and the time that the tabform is loading with the ng-include. 

The dynamic height is working OK when there is already data in the MD-TAB-BODY. But when you load a servoy-form with ng-include="getActiveTabUrl(tab)  the height is not taken from the tabform content. Tab-form data is not visible. I think the height of md-dynamic-height is calculated before the form-data is included into the MD-TAB-BODY. 
Is there a solution for this? 

Set the tab-height with "style: min-height" is also possible. But with responsive design not easy.

**Comment by paronne** [comment]
Hi, adding md-dynamic-height to the MD-TABS would work only if the contained form is a Responsive form. The height will be flatted to 0 instead if the contained form is non-responsive.
To better support dynamic content the height property has been added to the 'tab' definition; 
The height property is used only if the TabPanel is in a responsive form.
If the height is not set (Default) the tabpanel will be as high as the containef form, in case the latter is a responsive form. If the contained form instead is an anchored form, the height value is required.
If you are running from source check commits:
https://github.com/Servoy/angularmaterial/commit/18a9210d3a03924a7fb042fb1aa4d94819f6ea71
https://github.com/Servoy/angularmaterial/commit/f1023a7f63d35c9f06602e225f9b087db49294bf
